# INFO CONFIG
# MiniMessage Support & Chat color codes are supported
#
#
#
#
commands:
  discord:
    - "Entra ora nel <blue>discord&r! "
    - "<click:open_url:'INSERT.URL.HERE'>https://discord.gg/INVITE</click>"